### ISSUE TITLE
bknr-web will not load with Hunchentoot 1.1.1 per acceptor-dispatch-request

### ISSUE THREAD

**Issue by mon-key** [hanshuebner/bknr-web#1]
bknr-web will not load with Hunchentoot 1.1.1 per acceptor-dispatch-request  
It may be helpful to mention this in the README or provide a conditional around Hunchentoots ASDF version

**Comment by hanshuebner** [comment]
Given that there is no documentation at present, just mentioning that a current Hunchentoot version is required does not seem like being much of an improvement.  I had the editor open, but then, what would be needed is a complete dependency list.

That said, if you have any documentation patches to share, please do.  Thanks!
